# List of supported Midpen zones for alerts and notifications
ZONES = [
    "Bear Creek Redwoods",
    "Coal Creek",
    "El Corte de Madera",
    "El Sereno",
    "Fremont Older",
    "Foothills",
    "La Honda Creek",
    "Long Ridge",
    "Los Trancos",
    "Monte Bello",
    "Picchetti Ranch",
    "Pulgas Ridge",
    "Purisima",
    "Ravenswood",
    "Russian Ridge",
    "Saratoga Gap",
    "Sierra Azul",
    "Skyline Ridge",
    "St. Joseph’s Hill",
    "Stevens Canyon",
    "Thornewood",
    "Windy Hill",
    "Rancho San Antonio",
    "Miramontes Ridge",
    "Teague Hill",
    "Tunitas Creek"
]
